import { describe, expect, it } from "vitest";
import type { Decade, PlayerStats, Player, Position, Roster } from "../../types";
import { POSITIONS } from "../../types";
import { createRng, pick, randInt, shuffle } from "../rng";
import { dateKey, dailySeed } from "../daily";
import { teamStrength } from "../strength";
import { simulateSeason } from "../season";
import { simulateSeries } from "../series";
import { shareText } from "../share";

// NOTE: wheel.ts / roster.ts / index.ts are intentionally not imported
// here — they depend on src/data/players/* franchise files that are
// generated by a separate agent and may not exist yet.

// ---------- synthetic rosters (no data files needed) ----------

function makePlayer(name: string, pos: Position, stats: PlayerStats): Player {
  return {
    id: `${name.toLowerCase().replace(/\s+/g, "-")}-test-1990s`,
    name,
    franchiseId: "test",
    decade: "1990s" as Decade,
    positions: [pos],
    stats,
    years: "1990–1999",
  };
}

function makeRoster(statsByPos: Record<Position, PlayerStats>): Roster {
  const roster = {} as Roster;
  for (const pos of POSITIONS) {
    roster[pos] = makePlayer(`Player ${pos}`, pos, statsByPos[pos]);
  }
  return roster;
}

// All-time legends: ~26-30 ppg each with strong ast/reb support.
const SUPERTEAM = makeRoster({
  PG: { pts: 28, reb: 6.0, ast: 9.5, stl: 2.1, blk: 0.3 },
  SG: { pts: 30, reb: 6.3, ast: 5.4, stl: 2.3, blk: 0.8 },
  SF: { pts: 27, reb: 7.5, ast: 7.2, stl: 1.6, blk: 0.8 },
  PF: { pts: 26, reb: 12.5, ast: 4.0, stl: 1.0, blk: 1.8 },
  C: { pts: 28, reb: 13.0, ast: 3.5, stl: 0.7, blk: 2.8 },
});

// Average role players, ~12 ppg each.
const SCRUB_TEAM = makeRoster({
  PG: { pts: 12, reb: 3.0, ast: 4.5, stl: 0.9, blk: 0.1 },
  SG: { pts: 13, reb: 3.5, ast: 2.5, stl: 0.8, blk: 0.2 },
  SF: { pts: 12, reb: 4.5, ast: 2.0, stl: 0.8, blk: 0.4 },
  PF: { pts: 11, reb: 6.0, ast: 1.5, stl: 0.5, blk: 0.6 },
  C: { pts: 12, reb: 6.5, ast: 1.0, stl: 0.4, blk: 0.9 },
});

// Genuinely weak: end-of-bench stat lines.
const WEAK_TEAM = makeRoster({
  PG: { pts: 8, reb: 2.0, ast: 3.0, stl: 0.6, blk: 0.1 },
  SG: { pts: 9, reb: 2.5, ast: 1.5, stl: 0.5, blk: 0.1 },
  SF: { pts: 8, reb: 3.0, ast: 1.5, stl: 0.5, blk: 0.3 },
  PF: { pts: 7, reb: 4.5, ast: 1.0, stl: 0.4, blk: 0.4 },
  C: { pts: 8, reb: 5.0, ast: 0.8, stl: 0.3, blk: 0.7 },
});

// ---------- rng ----------

describe("rng", () => {
  it("is deterministic: same seed yields the same sequence", () => {
    const a = createRng("hoops-seed");
    const b = createRng("hoops-seed");
    for (let i = 0; i < 100; i++) expect(a()).toBe(b());
  });

  it("yields different sequences for different seeds", () => {
    const a = createRng("seed-one");
    const b = createRng("seed-two");
    const seqA = Array.from({ length: 10 }, () => a());
    const seqB = Array.from({ length: 10 }, () => b());
    expect(seqA).not.toEqual(seqB);
  });

  it("stays in [0,1) and helpers respect bounds", () => {
    const rng = createRng("bounds");
    for (let i = 0; i < 1000; i++) {
      const v = rng();
      expect(v).toBeGreaterThanOrEqual(0);
      expect(v).toBeLessThan(1);
    }
    const r2 = createRng("bounds2");
    for (let i = 0; i < 200; i++) {
      const n = randInt(r2, 3, 7);
      expect(n).toBeGreaterThanOrEqual(3);
      expect(n).toBeLessThanOrEqual(7);
    }
    const arr = [1, 2, 3, 4, 5];
    const shuffled = shuffle(createRng("s"), arr);
    expect(arr).toEqual([1, 2, 3, 4, 5]); // input untouched
    expect([...shuffled].sort()).toEqual([1, 2, 3, 4, 5]);
    expect(arr).toContain(pick(createRng("p"), arr));
  });
});

// ---------- daily ----------

describe("daily", () => {
  it("formats UTC date keys and seeds", () => {
    const d = new Date(Date.UTC(2026, 5, 10, 3, 4, 5));
    expect(dateKey(d)).toBe("2026-06-10");
    expect(dailySeed(d)).toBe("daily-2026-06-10");
  });
});

// ---------- season ----------

describe("season", () => {
  it("is deterministic for the same roster + seed", () => {
    const a = simulateSeason(SUPERTEAM, "season-seed-42");
    const b = simulateSeason(SUPERTEAM, "season-seed-42");
    expect(a).toEqual(b);
    const c = simulateSeason(SUPERTEAM, "season-seed-43");
    expect(a.games.map((g) => g.win)).not.toEqual(c.games.map((g) => g.win));
  });

  it("produces 82 well-formed games", () => {
    const r = simulateSeason(SCRUB_TEAM, "shape-check");
    expect(r.games).toHaveLength(82);
    expect(r.wins + r.losses).toBe(82);
    expect(r.wins).toBe(r.games.filter((g) => g.win).length);
    for (const g of r.games) {
      if (g.win) expect(g.teamScore).toBeGreaterThan(g.oppScore);
      else expect(g.teamScore).toBeLessThan(g.oppScore);
    }
    const firstLossGame = r.games.find((g) => !g.win);
    expect(r.firstLoss).toBe(firstLossGame ? firstLossGame.gameNo : null);
  });

  it("calibration: superteam averages >= 75 wins and hits 82-0", () => {
    const seeds = 200;
    let totalWins = 0;
    let perfect = 0;
    for (let i = 0; i < seeds; i++) {
      const r = simulateSeason(SUPERTEAM, `calibration-super-${i}`);
      totalWins += r.wins;
      if (r.wins === 82) {
        perfect++;
        expect(r.firstLoss).toBeNull();
      }
    }
    const avg = totalWins / seeds;
    console.log(
      `[calibration] superteam avg wins=${avg.toFixed(2)}, 82-0 rate=${(
        (perfect / seeds) * 100
      ).toFixed(1)}% (overall=${teamStrength(SUPERTEAM).overall})`,
    );
    expect(avg).toBeGreaterThanOrEqual(75);
    expect(perfect).toBeGreaterThanOrEqual(1);
  });

  it("calibration: scrub team averages <= 55 wins", () => {
    const seeds = 200;
    let totalWins = 0;
    for (let i = 0; i < seeds; i++) {
      totalWins += simulateSeason(SCRUB_TEAM, `calibration-scrub-${i}`).wins;
    }
    const avg = totalWins / seeds;
    console.log(
      `[calibration] scrub avg wins=${avg.toFixed(2)} (overall=${
        teamStrength(SCRUB_TEAM).overall
      })`,
    );
    expect(avg).toBeLessThanOrEqual(55);
  });

  it("calibration: weak roster stays under 30 wins on average", () => {
    let totalWins = 0;
    for (let i = 0; i < 100; i++) {
      totalWins += simulateSeason(WEAK_TEAM, `calibration-weak-${i}`).wins;
    }
    const avg = totalWins / 100;
    console.log(
      `[calibration] weak avg wins=${avg.toFixed(2)} (overall=${
        teamStrength(WEAK_TEAM).overall
      })`,
    );
    expect(avg).toBeLessThan(30);
  });
});

// ---------- strength ----------

describe("strength", () => {
  it("handles null slots safely and keeps fields in range", () => {
    const empty: Roster = { PG: null, SG: null, SF: null, PF: null, C: null };
    const r = teamStrength(empty);
    expect(r.chemistry).toBe(0);
    expect(r.offense).toBe(95);
    expect(Number.isFinite(r.overall)).toBe(true);
    const full = teamStrength(SUPERTEAM);
    expect(full.chemistry).toBeGreaterThan(0);
    expect(full.chemistry).toBeLessThanOrEqual(1);
    expect(full.offense).toBeGreaterThanOrEqual(95);
    expect(full.offense).toBeLessThanOrEqual(135);
    expect(full.overall).toBeGreaterThan(teamStrength(SCRUB_TEAM).overall);
  });
});

// ---------- series ----------

describe("series", () => {
  it("is deterministic per seed", () => {
    const a = simulateSeries(SUPERTEAM, SCRUB_TEAM, "series-seed");
    const b = simulateSeries(SUPERTEAM, SCRUB_TEAM, "series-seed");
    expect(a).toEqual(b);
  });

  it("ends at 4 wins with plausible scores", () => {
    const r = simulateSeries(SCRUB_TEAM, SUPERTEAM, "series-shape");
    expect(Math.max(r.aWins, r.bWins)).toBe(4);
    expect(Math.min(r.aWins, r.bWins)).toBeLessThanOrEqual(3);
    expect(r.games.length).toBe(r.aWins + r.bWins);
    for (const g of r.games) {
      expect(g.aScore).not.toBe(g.bScore);
      expect(Math.min(g.aScore, g.bScore)).toBeGreaterThanOrEqual(90);
      expect(Math.max(g.aScore, g.bScore)).toBeLessThanOrEqual(135);
    }
    expect(r.winner).toBe(r.aWins > r.bWins ? "a" : "b");
  });

  it("a much stronger roster wins the series in >80% of seeds (both slots)", () => {
    let strongAsA = 0;
    let strongAsB = 0;
    for (let i = 0; i < 100; i++) {
      if (simulateSeries(SUPERTEAM, SCRUB_TEAM, `series-${i}`).winner === "a") {
        strongAsA++;
      }
      if (simulateSeries(SCRUB_TEAM, SUPERTEAM, `series-${i}`).winner === "b") {
        strongAsB++;
      }
    }
    console.log(
      `[calibration] strong roster series win rate: slot a=${strongAsA}%, slot b=${strongAsB}%`,
    );
    expect(strongAsA).toBeGreaterThan(80);
    expect(strongAsB).toBeGreaterThan(80);
  });
});

// ---------- share ----------

describe("shareText", () => {
  it("contains the header, record, and 82 squares", () => {
    const result = simulateSeason(SUPERTEAM, "share-seed");
    const text = shareText(result, { mode: "daily", dateKey: "2026-06-10" });
    expect(text).toContain("🏀 Hoops 82–0 · Daily 2026-06-10");
    expect(text).toContain(`Record: ${result.wins}–${result.losses}`);
    const squares = (text.match(/🟩|🟥/g) ?? []).length;
    expect(squares).toBe(82);
    expect((text.match(/🟩/g) ?? []).length).toBe(result.wins);
    expect(text).toContain("https://krhamby.github.io/Hoops/");
    // rows of 14: 5 full rows + one row of 12
    const rows = text.split("\n").filter((l) => /^(🟩|🟥)+$/.test(l));
    expect(rows).toHaveLength(6);
    expect(rows.slice(0, 5).every((row) => (row.match(/🟩|🟥/g) ?? []).length === 14)).toBe(true);

    expect(shareText(result, { mode: "free" })).toContain("Free Play");
    expect(shareText(result, { mode: "versus" })).toContain("Versus");
  });
});
